import type { Metadata } from "next";
import SideNav from "@/app/ui/sidenav";
import "@sakun/system.css";
import "@/app/globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className="flex flex-row h-screen">
					<SideNav />
					<div className="window">
						<div className="title-bar">
							<h1 className="title">Mistigri</h1>
						</div>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
